{
  "comments": [
    {
      "key": {
        "uuid": "5a93c517_8e67de4c",
        "filename": "appc-config/appc-config-adaptor/provider/src/main/java/org/onap/appc/ccadaptor/SshJcraftWrapper.java",
        "patchSetId": 1
      },
      "lineNbr": 551,
      "author": {
        "id": 49
      },
      "writtenOn": "2018-02-23T22:35:31Z",
      "side": 0,
      "message": "It looks like an exception used to be thrown by this method. But, now with the try block, the exception will not be thrown. Maybe it should be re-thrown from the catch block?",
      "revId": "0df5aa1d2f10f0c20d80dfaf0311891e6d1b5974",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": false
    }
  ]
}